version: "3"
services:
  bootstrap:
    image: quorumcontrol/tupelo:protobuf-transactions
    command: ["bootstrap-node", "-p", "34001"]
    environment:
      TUPELO_NODE_BLS_KEY_HEX: "0x1ef1cf13d52b2dbf3134d7fff6aa617c5cdac42ed89bd20007bfc93d00f0d0c6"
      TUPELO_NODE_ECDSA_KEY_HEX: "0xe2c0b170c56ff0bf08c7376f1ca4bd5cbe481a85f6cdb3de609863e25dce613a"
      # Bootstrap to self so that this node doesn't connect to the remote network
      TUPELO_BOOTSTRAP_NODES: "/ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5"
    networks:
      default:
        ipv4_address: 172.16.239.10
    ports:
      - "34001:34001"

  node0:
    image: quorumcontrol/tupelo:protobuf-transactions
    depends_on:
      - bootstrap
    volumes:
      - ./devdocker/localkeys:/bootstrap-keys
    command: ["-L", "info","test-node", "-k", "/bootstrap-keys"]
    environment:
      TUPELO_NODE_BLS_KEY_HEX: "0x4344e3372f1b790016ed86400611fab64d0bba91136518685a7ce34106f1c759"
      TUPELO_NODE_ECDSA_KEY_HEX: "0xc09363e85290020c132053f029f23988d4e35c521b0698312e0071f3e5d0e023"
      TUPELO_BOOTSTRAP_NODES: "/ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5"

  node1:
    image: quorumcontrol/tupelo:protobuf-transactions
    depends_on:
      - bootstrap
    volumes:
      - ./devdocker/localkeys:/bootstrap-keys
    command: ["test-node", "-k", "/bootstrap-keys"]
    environment:
      TUPELO_NODE_BLS_KEY_HEX: "0x39a9b8ab3266811852b8b18d1fd0562ffc907f3ecba297c9b2a89f742d349dc9"
      TUPELO_NODE_ECDSA_KEY_HEX: "0xa1b8b9936d8072b1a16311aee414289a5f8070acff847588386738d6d686fc9b"
      TUPELO_BOOTSTRAP_NODES: "/ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5"
 
  node2:
    image: quorumcontrol/tupelo:protobuf-transactions
    depends_on:
      - bootstrap
    volumes:
      - ./devdocker/localkeys:/bootstrap-keys
    command: ["test-node", "-k", "/bootstrap-keys"]
    environment:
      TUPELO_NODE_BLS_KEY_HEX: "0x558a546adacea3d761741bf4a6415ef2eeb85bfa457036b59564fa88ee276cf5"
      TUPELO_NODE_ECDSA_KEY_HEX: "0x251b3227fc393f810846f170c1534c2787721a4385d4711d93321302bf023bab"
      TUPELO_BOOTSTRAP_NODES: "/ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
