# This file relies on a running localnet - `make localnet` will run the correct docker-compose for you.
version: "3"
services:
  game:
    build: ./devdocker
    depends_on:
      - inkfaucet
    command: ["go", "run", "main.go", "-disablewebview=true", "-localnet=true"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K
      INK_DID:

  game2:
    build: ./devdocker
    command: ["go", "run", "main.go", "-disablewebview=true", "-localnet=true"]
    depends_on:
      - inkfaucet
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8090:8080
      - 8091:8081
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K
      INK_DID:

  inkfaucet:
    build: ./devdocker
    command: ["go", "run", "-tags=internal", "inkfaucet/main.go", "-local=true", "-deposit=${TOKEN_PAYLOAD}"]
    depends_on:
      - localstack
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
      - ./devdocker/devink_state:/root/.config/tupelo:delegated
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K
      INK_DID:
      TOKEN_PAYLOAD:
      INK_FAUCET_KEY:

  devink:
    build: ./devdocker
    command: ["go", "run", "-tags=internal", "devink/main.go", "${INK_FAUCET_KEY}"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
      - ./devdocker/devink_state:/root/.config/tupelo:delegated
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      INK_FAUCET_KEY:

  invite:
    build: ./devdocker
    command: ["go", "run", "-tags=internal", "inkfaucet/main.go", "-local=true", "-invite=true"]
    depends_on:
      - localstack
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
      - ./devdocker/devink_state:/root/.config/tupelo:delegated
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K
      INK_DID:
      INK_FAUCET_KEY:

  game-testnet:
    build: ./devdocker
    command: ["go", "run", "main.go", "-disablewebview=true"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - ./devdocker/testnetkeys:/app/devdocker/localkeys:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go

  importer:
    build: ./devdocker
    depends_on:
      - inkfaucet
    command: ["go", "run", "importer/cmd/importer/main.go", "-local=true", "-path=importer/import-example"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      BUILD: internal
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K

  importer-testnet:
    build: ./devdocker
    command: ["go", "run", "importer/cmd/importer/main.go", "-local=false", "-path=importer/import-example"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - ./devdocker/testnetkeys:/app/devdocker/localkeys:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      BUILD: internal

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3

  integration:
    build: ./devdocker
    command:
      - go
      - test
      - -v
      - -tags='integration internal'
      - -timeout=5m
      - ${TEST_PACKAGE-./...}
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K

networks:
  default:
    external:
      name: jasons-game_default
