# This file relies on a running localnet - `make localnet` will run the correct docker-compose for you.
version: "3"
services:
  game:
    build: ./devdocker
    depends_on:
      - jason
      - jasonblock
    command: ["go", "run", "main.go", "-disablewebview=true", "-localnet=true"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K

  game2:
    build: ./devdocker
    command: ["go", "run", "main.go", "-disablewebview=true", "-localnet=true"]
    depends_on:
      - jason
      - jasonblock
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8090:8080
      - 8091:8081
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K

  jasonblock:
    build: ./devdocker
    command: ["go", "run", "jason/main.go", "-port=34001", "-local=true", "-enable-blockstore=true"]
    depends_on:
      - localstack
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - ./devdocker/testnetkeys:/app/devdocker/localkeys:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K

  jason:
    build: ./devdocker
    command: ["go", "run", "jason/main.go", "-port=34001", "-local=true"]
    depends_on:
      - localstack
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - ./devdocker/testnetkeys:/app/devdocker/localkeys:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
      - ./devdocker/jason/private.key:/root/.config/tupelo/jasons-game/private.key
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K
    networks:
      default:
        ipv4_address: 172.16.239.100

  game-testnet:
    build: ./devdocker
    command: ["go", "run", "main.go", "-disablewebview=true"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - ./devdocker/testnetkeys:/app/devdocker/localkeys:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      PPROF_ENABLED: "true"
      GOPATH: /go
  
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3

  integration:
    build: ./devdocker
    depends_on:
      - jason
    command:
      - go
      - test
      - -v
      - -tags=integration
      - -timeout=5m
      - ${TEST_PACKAGE-./...}
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5
      JASON_BOOTSTRAP_NODES: /ip4/172.16.239.100/tcp/34001/ipfs/16Uiu2HAmBL6Xz9ichyunCexiqomcHyzVpKKmxAMgUusksBZzzM3K

networks:
  default:
    external:
      name: jasons-game_default
