version: "3"
services:
  bootstrap:
    image: quorumcontrol/tupelo:master
    command: ["bootstrap-node", "--config", "/configs/bootstrap/config.toml", "-L", "${TUPELO_LOG_LEVEL:-error}"]
    volumes:
      - ./devdocker/localkeys:/configs      
    networks:
      default:
        ipv4_address: 172.16.239.10

  community:
    image: quorumcontrol/community:master
    depends_on:
      - bootstrap
    command: ["-c", "/configs/community/config.toml"]
    volumes:
      - ./devdocker/localkeys:/configs
    networks:
      default:
        ipv4_address: 172.16.239.100

  node0:
    image: quorumcontrol/tupelo:master
    depends_on:
      - bootstrap
    command: ["test-node", "--config", "/configs/node0/config.toml", "-L", "${TUPELO_LOG_LEVEL:-error}"]
    volumes:
      - ./devdocker/localkeys:/configs

  node1:
    image: quorumcontrol/tupelo:master
    depends_on:
      - bootstrap
    command: ["test-node", "--config", "/configs/node1/config.toml", "-L", "${TUPELO_LOG_LEVEL:-error}"]
    volumes:
      - ./devdocker/localkeys:/configs
  
  node2:
    image: quorumcontrol/tupelo:master
    depends_on:
      - bootstrap
    command: ["test-node", "--config", "/configs/node2/config.toml", "-L", "${TUPELO_LOG_LEVEL:-error}"]
    volumes:
      - ./devdocker/localkeys:/configs

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24