# This file relies on a running localnet - `make localnet` will run the correct docker-compose for you.
version: "3"
services:
  game:
    build: ./devdocker
    command: ["go", "run", "server/test/main.go"]
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    ports:
      - 8080:8080
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5

  integration:
    build: ./devdocker
    command:
      - go
      - test
      - -v
      - -tags=integration
      - -timeout=2m
      - ${TEST_PACKAGE-./...}
    volumes:
      - .:/app:delegated
      - ./devdocker/.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
    environment:
      GOPATH: /go
      TUPELO_BOOTSTRAP_NODES: /ip4/172.16.239.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5

networks:
  default:
    external:
      name: jasons-game_default