version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.6
        environment:
          GOPROXY: https://proxy.golang.org
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "27:e7:80:85:93:ac:92:d3:5a:3e:5c:a5:53:e2:fd:d3"
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - restore_cache:
          keys:
            - v1-node-modules-frontend-{{ checksum "frontend/jasons-game/package-lock.json" }}
      - run: ./scripts/build-within-docker.sh
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - save_cache:
          key: v1-node-modules-frontend-{{ checksum "frontend/jasons-game/package-lock.json" }}
          paths:
            - "v1-frontend/jasons-game/node_modules"
      - store_test_results:
          path: test_results
