NotaryGroupConfig = "../notarygroup.toml"
Key = "0x91314a17c141f39a0b53a1d3ed7534e3dc829d144663bd5e18515c24edd81c04"
Port = 34001

Name = "jasonsgame"
Shards = 1024
CacheMessages = false
CacheBlocks = true
RebroadcastCommit = true
TrackPeers = false

[Storage]
Kind = "memory"

[logs]
tupelocache = "debug"
dht = "debug"